//
// Created by fgd on 2019/4/28.
//

#ifndef NLOGGER_NLOGGER_ERROR_CODE_H
#define NLOGGER_NLOGGER_ERROR_CODE_H

#endif //NLOGGER_NLOGGER_ERROR_CODE_H
#define ERROR_CODE_CHANGE_CACHE_MODE_TO_MEMORY 3
#define ERROR_CODE_NEW_LOG_FILE_OPENED 2
#define ERROR_CODE_OK 1
#define ERROR_CODE_ILLEGAL_ARGUMENT (-1)
#define ERROR_CODE_MALLOC_NLOGGER_STRUCT (-2)
#define ERROR_CODE_MALLOC_CACHE_DIR_STRING (-3)
#define ERROR_CODE_CREATE_LOG_CACHE_DIR_FAILED (-4)
#define ERROR_CODE_MALLOC_LOG_FILE_DIR_STRING (-5)
#define ERROR_CODE_NEED_INIT_NLOGGER_BEFORE_ACTION (-6)

#define ERROR_CODE_MALLOC_LOG_FILE_PATH_STRING (-7)
#define ERROR_CODE_MALLOC_LOG_FILE_NAME_STRING (-8)

#define ERROR_CODE_OPEN_LOG_FILE_FAILED (-9)

#define ERROR_CODE_MAP_LOG_NAME_TO_CACHE_FAILED (-10)

#define ERROR_CODE_INIT_CACHE_FAILED (-11)
