//
// Created by Nie R on 2019/4/30.
//

#ifndef NLOGGER_NLOGGER_CONSTANTS_H
#define NLOGGER_NLOGGER_CONSTANTS_H

#endif //NLOGGER_NLOGGER_CONSTANTS_H
#define NLOGGER_CACHE_DIR  "nlogger_cache"
#define NLOGGER_CACHE_FILE_NAME "cache.mmap"

//#define NLOGGER_MMAP_CACHE_HEADER_KEY_VERSION "version"
//#define NLOGGER_MMAP_CACHE_HEADER_KEY_FILE "file"
//#define NLOGGER_MMAP_CACHE_HEADER_KEY_DATE "date"


//nier>>3381160
//fgd>>101315
//java>>3254818
//kotlin>>-1125574399

//#define NLOGGER_MMAP_CACHE_CONTENT_HEAD_MAGIC 3381160
//#define NLOGGER_MMAP_CACHE_CONTENT_TAIL_MAGIC 101315
//
//#define NLOGGER_MMAP_CACHE_HEADER_HEAD_MAGIC 3254818
//#define NLOGGER_MMAP_CACHE_HEADER_TAIL_MAGIC (-1125574399)

#define NLOGGER_MMAP_CACHE_CONTENT_HEAD_MAGIC 0x003397A8//nier>>3381160
#define NLOGGER_MMAP_CACHE_CONTENT_TAIL_MAGIC 0x00018BC3//fgd>>101315
#define NLOGGER_MMAP_CACHE_HEADER_HEAD_MAGIC 0x0031AA22//java>>3254818
#define NLOGGER_MMAP_CACHE_HEADER_TAIL_MAGIC 0xBCE91901//kotlin>>-1125574399

#define NLOGGER_MMAP_CACHE_CONTENT_HEAD_TAG '\1'
#define NLOGGER_MMAP_CACHE_CONTENT_TAIL_TAG '\0'

#define NLOGGER_MMAP_CACHE_HEADER_HEAD_TAG '^'
#define NLOGGER_MMAP_CACHE_HEADER_TAIL_TAG '$'

#define NLOGGER_WRITE_SEGMENT_LENGTH (20 * 1024)

#define NLOGGER_CONTENT_LENGTH_BYTE_SIZE 3
#define NLOGGER_CONTENT_SUB_SECTION_LENGTH_BYTE_SIZE 4

#define NLOGGER_ZLIB_COMPRESS_CHUNK_SIZE (15 * 1024)

#define NLOGGER_AES_ENCRYPT_UNIT 16

#define NLOGGER_COMPRESS_SECTION_THRESHOLD (5 * 1024)

#define NLOGGER_FLUSH_MMAP_CACHE_SIZE_THRESHOLD (50 * 1024)

#define NLOGGER_FLUSH_MEMORY_CACHE_SIZE_THRESHOLD (10 * 1024)

#define NLOGGER_MMAP_CACHE_MAX_HEADER_CONTENT_SIZE (2 * 1024)

