//
// Created by Nie R on 2019/4/30.
//

#ifndef NLOGGER_NLOGGER_CONSTANTS_H
#define NLOGGER_NLOGGER_CONSTANTS_H

#endif //NLOGGER_NLOGGER_CONSTANTS_H
#define NLOGGER_CACHE_DIR  "nlogger_cache"
#define NLOGGER_CACHE_FILE_NAME "cache.mmap"

#define NLOGGER_MMAP_CACHE_HEADER_KEY_VERSION "version"
#define NLOGGER_MMAP_CACHE_HEADER_KEY_FILE "file"
#define NLOGGER_MMAP_CACHE_HEADER_KEY_DATE "date"

#define NLOGGER_MMAP_CACHE_HEADER_HEAD_TAG '^'
#define NLOGGER_MMAP_CACHE_HEADER_TAIL_TAG '$'

#define NLOGGER_VERSION 1

#define NLOGGER_CONTENT_LENGTH_BYTE_SIZE 3
